bug-reports
alessioC42/SPH-vertretungsplan pull request #39
Opened 2023-12-10 12:39 UTC by alessioC42

Send bug reports from the app with useful debug metadata to the developers. 
Using coudflare workers as storage. 

- [x] setup worker (backend)
- [ ] some client (most likely an webpage)
- [ ] app integration

2023-12-12 16:27 UTC, alessioC42 commented
@kurwjan ich kann "Nachrichten - Beta Version" nicht hinzufügen. Es müssen bei "//TODO: add conversations" die Benachrichtigungen gefetcht werden.

2023-12-13 10:37 UTC, alessioC42 commented
Er sollte jetzt mit den "Nachrichten - Beta Version" klar kommen.

2023-12-13 13:24 UTC, kurwjan requested changes
Wenn man ohne Metadaten sendet, funktioniert alles.
Mit Metadaten (und Nachrichten Support) gibt es Fehlermeldung:
```
I/flutter (22791): DioException [bad response]: This exception was thrown because the response has a status code of 500 and RequestOptions.validateStatus was configured to throw for this status code.
I/flutter (22791): The status code of 500 has the following meaning: "Server error - the server failed to fulfil an apparently valid request"
I/flutter (22791): Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
I/flutter (22791): In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.
I/flutter (22791): 
```

2023-12-13 18:32 UTC, kurwjan approved these changes
Geil

2023-12-14 10:04 UTC, merged